sudo: required
services:
  - docker

before_install:
  - docker build -t fsalikutluk/docker-react -f Dockerfile.dev .

script:
  - docker run fsalikutluk/docker-react npm run test -- --coverage

deploy:
  